apiVersion: v1
kind: Service
metadata:
  name: aynaorder
spec:
  selector:
    app: aynaorder  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 9105  # Service port (port exposed on the Service)
      targetPort: 9105  # Port your application is listening on inside the container
      nodePort: 30019  # NodePort number (replace with your desired port number)
  type: NodePort  # Expose the Service on a NodePort
