                        FROM eclipse-temurin:latest
						
						RUN pwd
						
						RUN ls -al
						
						RUN dir
						
						COPY  target/aynaorder-0.0.1-SNAPSHOT.jar /aynaorder/aynaorder.jar
						
						WORKDIR /aynaorder
						
						RUN pwd
						
						RUN ls -al
                                             
                       
						
						
                        CMD ["java", "-jar", "aynaorder.jar"]
                    