                        FROM eclipse-temurin:latest
						
						RUN pwd
						
						RUN ls -al
						
						RUN dir
						
						COPY  target/aynastock-0.0.1-SNAPSHOT.jar /aynastock/aynastock.jar
						
						WORKDIR /aynastock
						
						RUN pwd
						
						RUN ls -al
                                             
                       
						
						
                        CMD ["java", "-jar", "aynastock.jar"]
                    