                        FROM eclipse-temurin:latest
						
						RUN pwd
						
						RUN ls -al
						
						RUN dir
						
						COPY  target/aynaserviceregistry-0.0.1-SNAPSHOT.jar /aynaserviceregistry/aynaserviceregistry.jar
						
						WORKDIR /aynaserviceregistry
						
						RUN pwd
						
						RUN ls -al
                                             
                       
						
						
                        CMD ["java", "-jar", "aynaserviceregistry.jar"]
                    