                        FROM eclipse-temurin:latest
						
						RUN pwd
						
						RUN ls -al
						
						RUN dir
						
						COPY  target/aynaproduct-0.0.1-SNAPSHOT.jar /aynaproduct/aynaproduct.jar
						
						WORKDIR /aynaproduct
						
						RUN pwd
						
						RUN ls -al
                                             
                       
						
						
                        CMD ["java", "-jar", "aynaproduct.jar"]
                    